/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supertlon.vistas;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.supertlon.funcionalidad.*; 
import java.time.LocalDate;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author Ivar
 */


public class GestionProfesoresArticulosBusqueda extends javax.swing.JFrame {
    private Supertlon controlador;
    public GestionProfesoresArticulosBusqueda(Supertlon supertlon) {
        this.controlador = supertlon;
        initComponents();
    }
    

    /**
     * Creates new form GestionProfesoresArticulosBusqueda
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAcum = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtHorasAcum = new javax.swing.JTextField();
        btnEliminarArticulo1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxHorasDeUso = new javax.swing.JComboBox<>();
        btnCrearArticulo1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/images/city.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Profesores");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setText("Busqueda Articulos y Amotizaciones Acumuladas");

        tblAcum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Articulo", "Amortizacion Acumulada"
            }
        ));
        jScrollPane2.setViewportView(tblAcum);

        jLabel4.setText("Ingrese Horas de uso Acumuladas");

        btnEliminarArticulo1.setBackground(new java.awt.Color(51, 153, 255));
        btnEliminarArticulo1.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminarArticulo1.setText("Eliminar");
        btnEliminarArticulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArticulo1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Colchoneta Alta Densidad o Pesa Tobillera?");

        jComboBoxHorasDeUso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colchoneta Alta Densidad", "Pesa Tobillera" }));
        jComboBoxHorasDeUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHorasDeUsoActionPerformed(evt);
            }
        });

        btnCrearArticulo1.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearArticulo1.setForeground(new java.awt.Color(51, 51, 51));
        btnCrearArticulo1.setText("Cargar datos");
        btnCrearArticulo1.setActionCommand("Crear");
        btnCrearArticulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArticulo1ActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 51, 0));
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtHorasAcum, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBoxHorasDeUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCrearArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxHorasDeUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHorasAcum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarArticulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArticulo1ActionPerformed
      DefaultTableModel modeloTabla = (DefaultTableModel) tblAcum.getModel();
      modeloTabla.setRowCount(0);

    }//GEN-LAST:event_btnEliminarArticulo1ActionPerformed

    private void jComboBoxHorasDeUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHorasDeUsoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxHorasDeUsoActionPerformed

    private void btnCrearArticulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArticulo1ActionPerformed
        // TODO add your handling code here:
        cargarTabla();
        txtHorasAcum.setText("");
    }//GEN-LAST:event_btnCrearArticulo1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Ivan Original: Agrege esto que es para que, cuando abris una ventana, se cierre la anterior, si hace bugs o algo lo sacamos.

        GestionProfesoresArticulosBusquedaMenu admWindow = new GestionProfesoresArticulosBusquedaMenu(controlador);

        admWindow.setVisible(true);
        admWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed
        
private void cargarTabla() {
    String nombre = jComboBoxHorasDeUso.getSelectedItem().toString();
    String horasAcumText = txtHorasAcum.getText().trim(); // Obtener el texto y quitar espacios en blanco
    if (!horasAcumText.isEmpty()) { // Verificar si el texto no está vacío
        try {
            int horasUsoAcum = Integer.parseInt(horasAcumText);
            DefaultTableModel modeloTabla = new DefaultTableModel() {
               
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            String titulos[] = {"Articulo", "Amortizacion Acumulada"};
            modeloTabla.setColumnIdentifiers(titulos);

            List<Articulo> listaDeArticulos = controlador.getArticulos();

            if (listaDeArticulos != null) {
                for (Articulo articulos : listaDeArticulos) {
                    String amortAcum = articulos.calcularDeAmort(nombre, "", 0, horasUsoAcum, null);
                    Object[] object = {nombre, amortAcum};
                    modeloTabla.addRow(object);
                    break;
                }
            }
            tblAcum.setModel(modeloTabla);
        } catch (NumberFormatException e) {
            // Manejar la excepción si no se puede convertir a un número
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico válido para horas de uso acumuladas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Mostrar un mensaje o realizar alguna acción si el campo está vacío
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor para horas de uso acumuladas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
}
    public void mostrarMensaje (String mensaje, String tipo, String titulo) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if (tipo.equals("Error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearArticulo1;
    private javax.swing.JButton btnEliminarArticulo1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBoxHorasDeUso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAcum;
    private javax.swing.JTextField txtHorasAcum;
    // End of variables declaration//GEN-END:variables
}
