/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supertlon.vistas;

import org.supertlon.funcionalidad.Supertlon;
import org.supertlon.funcionalidad.*; 
import supertlon.vistas.Menu;

/**
 *
 * @author Ivar
 */
public class GestionProfesores extends javax.swing.JFrame {

    /**
     * Creates new form GestioProfesores
     */
    private Supertlon controlador;
    public GestionProfesores(Supertlon supertlon) {
        this.controlador = supertlon;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrearunaClase = new javax.swing.JButton();
        btnActualizarArticulos = new javax.swing.JButton();
        btnActualizarArticulos1 = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/images/city.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Profesores");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setText("Menu");

        btnCrearunaClase.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearunaClase.setForeground(new java.awt.Color(51, 51, 51));
        btnCrearunaClase.setText("Crear una Clase");
        btnCrearunaClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearunaClaseActionPerformed(evt);
            }
        });

        btnActualizarArticulos.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizarArticulos.setForeground(new java.awt.Color(51, 51, 51));
        btnActualizarArticulos.setText("Administrar Membresias");
        btnActualizarArticulos.setActionCommand("Actualizar  Articulos");
        btnActualizarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarArticulosActionPerformed(evt);
            }
        });

        btnActualizarArticulos1.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizarArticulos1.setForeground(new java.awt.Color(51, 51, 51));
        btnActualizarArticulos1.setText("Administrar Profesores");
        btnActualizarArticulos1.setActionCommand("Actualizar  Articulos");
        btnActualizarArticulos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarArticulos1ActionPerformed(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(204, 51, 0));
        btnSalir2.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir2.setText("Volver");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarArticulos1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(btnCrearunaClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(btnActualizarArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(120, 120, 120)
                .addComponent(btnCrearunaClase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnActualizarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnActualizarArticulos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearunaClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearunaClaseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GestionProfesorCrearClase gestprof = new GestionProfesorCrearClase(controlador);
        gestprof.setVisible(true);
        gestprof.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnCrearunaClaseActionPerformed

    private void btnActualizarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarArticulosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GestionAdministradorCrearNivelMembresia gestprof = new GestionAdministradorCrearNivelMembresia(controlador);
        gestprof.setVisible(true);
        gestprof.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnActualizarArticulosActionPerformed

    private void btnActualizarArticulos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarArticulos1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GestionAdministradorCrearProfesores gestprof = new GestionAdministradorCrearProfesores(controlador);
        gestprof.setVisible(true);
        gestprof.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnActualizarArticulos1ActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Ivan Original: Agrege esto que es para que, cuando abris una ventana, se cierre la anterior, si hace bugs o algo lo sacamos.

        Menu admWindow = new Menu(controlador);

        admWindow.setVisible(true);
        admWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalir2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarArticulos;
    private javax.swing.JButton btnActualizarArticulos1;
    private javax.swing.JButton btnCrearunaClase;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
