/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supertlon.vistas;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import org.supertlon.funcionalidad.*; 

/**
 *
 * @author Ivar
 */
public class GestionProfesoresArticulosBusqueda2 extends javax.swing.JFrame {
     private Supertlon controlador;
    /**
     * @param supertlon
     */
    public GestionProfesoresArticulosBusqueda2(Supertlon supertlon) {
        this.controlador = supertlon;
          initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFechaDeFabricacion = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFecha = new javax.swing.JTable();
        jComboBoxFechaDeFabricacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarArticulo2 = new javax.swing.JButton();
        btnCrearArticulo2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFechaDeFabricacion.setText("yyyy-MM-dd");
        getContentPane().add(txtFechaDeFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 272, -1));

        tblFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Articulo", "Amortizacion Acumulada"
            }
        ));
        jScrollPane3.setViewportView(tblFecha);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 56, 321, 190));

        jComboBoxFechaDeFabricacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colchoneta Liviana", "Pesa Tobillera Ironman" }));
        jComboBoxFechaDeFabricacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFechaDeFabricacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFechaDeFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        jLabel2.setText("Colchoneta Liviana o Pesa Tobillera Ironman?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, -1, -1));

        btnEliminarArticulo2.setBackground(new java.awt.Color(51, 153, 255));
        btnEliminarArticulo2.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminarArticulo2.setText("Eliminar");
        btnEliminarArticulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArticulo2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, 50));

        btnCrearArticulo2.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearArticulo2.setForeground(new java.awt.Color(51, 51, 51));
        btnCrearArticulo2.setText("Cargar datos");
        btnCrearArticulo2.setActionCommand("Crear");
        btnCrearArticulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArticulo2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 50));

        jLabel8.setText("Fecha de Fabricacion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, 126, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setText("Busqueda Articulos y Amotizaciones Acumuladas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 0, 537, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Profesores");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/images/city.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 290, 500));

        btnSalir.setBackground(new java.awt.Color(204, 51, 0));
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxFechaDeFabricacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFechaDeFabricacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFechaDeFabricacionActionPerformed

    private void btnEliminarArticulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArticulo2ActionPerformed
        // TODO add your handling code here:
      DefaultTableModel modeloTabla = (DefaultTableModel) tblFecha.getModel();
      modeloTabla.setRowCount(0);
    }//GEN-LAST:event_btnEliminarArticulo2ActionPerformed

    private void btnCrearArticulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArticulo2ActionPerformed
        // TODO add your handling code here:
        cargarTabla();

            
    }//GEN-LAST:event_btnCrearArticulo2ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Ivan Original: Agrege esto que es para que, cuando abris una ventana, se cierre la anterior, si hace bugs o algo lo sacamos.

        GestionProfesoresArticulosBusquedaMenu admWindow = new GestionProfesoresArticulosBusquedaMenu(controlador);

        admWindow.setVisible(true);
        admWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed
    private void cargarTabla() {
    String nombre = jComboBoxFechaDeFabricacion.getSelectedItem().toString();
    String horasAcumText = txtFechaDeFabricacion.getText();
    LocalDate fecha = LocalDate.parse(horasAcumText);
    if (!horasAcumText.isEmpty()) { // Verificar si el texto no está vacío
        try {
            DefaultTableModel modeloTabla = new DefaultTableModel() {
               
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            String titulos[] = {"Articulo", "Amortizacion Acumulada"};
            modeloTabla.setColumnIdentifiers(titulos);

            List<Articulo> listaDeArticulos = controlador.getArticulos();

            if (listaDeArticulos != null) {
                for (Articulo articulos : listaDeArticulos) {
                    String amortAcum = articulos.calcularDeAmort(nombre, "", 0, 0, fecha);
                    Object[] object = {nombre, amortAcum};
                    modeloTabla.addRow(object);
                    break;
                }
            }
            tblFecha.setModel(modeloTabla);
        } catch (NumberFormatException e) {
            // Manejar la excepción si no se puede convertir a un número
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico válido para horas de uso acumuladas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Mostrar un mensaje o realizar alguna acción si el campo está vacío
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor para horas de uso acumuladas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
}
    public void mostrarMensaje (String mensaje, String tipo, String titulo) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if (tipo.equals("Error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearArticulo2;
    private javax.swing.JButton btnEliminarArticulo2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBoxFechaDeFabricacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblFecha;
    private javax.swing.JTextField txtFechaDeFabricacion;
    // End of variables declaration//GEN-END:variables
}
